@startuml LexicalEnvironmentDeclaration
skinparam {
    FileFontSize 14
    ObjectAttributeFontSize 14
    ObjectFontSize 16
}
agent agent [
    null
]
file counter [
    let counter = 'hello';
]
object EnvironmentRecord
EnvironmentRecord : counter: 'hello'

left to right direction
counter .. EnvironmentRecord
EnvironmentRecord --> agent: Outer
@enduml
