@startuml LexicalEnvironmentVar
skinparam {
    FileFontSize 14
    ObjectAttributeFontSize 14
    ObjectFontSize 16
}
agent agent [
    null
]
file counter [
    let counter;
    counter = 'hello';
    counter = 'world';
]
object LexicalEnvironment
LexicalEnvironment : counter: <uninitialized>
LexicalEnvironment : counter: undefined
LexicalEnvironment : counter: 'hello'
LexicalEnvironment : counter: 'world'

left to right direction
counter .. LexicalEnvironment
LexicalEnvironment --> agent: Outer
@enduml