@startuml LexicalEnvironmentVar
skinparam {
    FileFontSize 14
    ObjectAttributeFontSize 14
    ObjectFontSize 16
}
agent agent [
    null
]
file counter [
    let counter;
    counter = 'hello';
    counter = 'world';
]
object EnvironmentRecord
EnvironmentRecord : counter: <uninitialized>
EnvironmentRecord : counter: undefined
EnvironmentRecord : counter: 'hello'
EnvironmentRecord : counter: 'world'

left to right direction
counter .. EnvironmentRecord
EnvironmentRecord --> agent: Outer
@enduml